// Advent of Code 2021
// Aaron Satterfield

// Day 1 - Sonar Sweep
// Part 1 ✅
// Part 2 ✅

// Day 2 - Dive!
// Part 1 ✅
// Part 2 ✅

// Day 3 - Binary Diagnostic
// Part 1 ✅
// Part 2 ✅

// Day 3 - Giant Squid
// Part 1 ✅
// Part 2 ✅
// Comments: Pretty sure this solution is worse than O(n!) 😭
