// Advent of Code 2021
// Aaron Satterfield

// Day 1 - Sonar Sweep
// Part 1 ✅
// Part 2 ✅

// Day 2 - Dive!
// Part 1 ✅
// Part 2 ✅

// Day 3 - Binary Diagnostic
// Part 1 ✅
// Part 2 ✅

// Day 4 - Giant Squid
// Part 1 ✅
// Part 2 ✅
// Comments: Pretty sure this solution is worse than O(n!) 😭

// Day 5 - Vents
// Part 1 ❌
// Part 2 ❌
// Comments: Yikes!


// Day 6 - Lanternfish
// Part 1 ✅
// Part 2 ❌
// Comments: Thought this would scale.... 

// Day 7 - The Treachery of Whales
// Part 1 ✅
// Part 2 ✅
